version: "3.7"

services:
  node:
    image: ghcr.io/sequentiaseq/sequentia-testnet:0.2@sha256:145fcd42cc4990151bc89aa9df932c09209aa08b5f2f92cfd555517a15fa7353
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 18776 # JSONRPC
      - 18777 # P2P PORT
    volumes:
      - ${APP_DATA_DIR}/data:/home/elements/.elements
    command:
      - -chain=test
      - -txindex=1
      - -rpcuser=sequentia
      - -rpcpassword=sequentia123
      - -rpcbind=0.0.0.0 # can we do better here?
      - -rpcallowip=0.0.0.0/0 # can we do better here?

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"
