services:
  app_proxy:
    environment:
      APP_HOST: $APP_SEQUENTIA_IP
      APP_PORT: 8080

  node:
    image: ghcr.io/sequentiaseq/sequentia-testnet:0.3@sha256:f6134fdb3812e5bf2be007b86f1b73484792250d7e030ae42b2bd2a33546b121
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_SEQUENTIA_NODE_RPC_PORT}:${APP_SEQUENTIA_NODE_RPC_PORT}"
      - "${APP_SEQUENTIA_NODE_P2P_PORT}:${APP_SEQUENTIA_NODE_P2P_PORT}"
    volumes:
      - $APP_DATA_DIR/data:/home/ubuntu/
    environment:
      TOR_PROXY_IP: $APP_SEQUENTIA_TOR_PROXY_IP
      TOR_PROXY_PORT: "9050"
      TOR_PROXY_CONTROL_PORT: "9051"
      TOR_PROXY_CONTROL_PASSWORD: "moneyprintergobrrr"
    command:
      - -chain=test
      - -txindex=1
      - -rpcauth=$APP_SEQUENTIA_RPC_AUTH
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -proxy=$APP_SEQUENTIA_TOR_PROXY_IP:9050
      - -torcontrol=$APP_SEQUENTIA_TOR_PROXY_IP:9051
      - -torpassword="moneyprintergobrrr"
      - -server=1
    networks:
      default:
        ipv4_address: $APP_SEQUENTIA_NODE_IP

  electrs:
      image: ghcr.io/sequentiaseq/sequentia-electrs:0.3@sha256:3f4a10fedf5cec29686b4bd3493c61764c47c2d7b3e1eea8d48811a438471374
      user: "1000:1000"
      depends_on:
        - node
      restart: on-failure
      ports:
        - "${APP_SEQUENTIA_ELECTRS_RPC_PORT}:${APP_SEQUENTIA_ELECTRS_RPC_PORT}"
        - "${APP_SEQUENTIA_ELECTRS_WEB_PORT}:${APP_SEQUENTIA_ELECTRS_WEB_PORT}"
      volumes:
        - $APP_DATA_DIR/data/:/home/ubuntu/
      command:
        --network testnet
        --db-dir /home/ubuntu/electrs
        --daemon-rpc-addr $APP_SEQUENTIA_NODE_IP:$APP_SEQUENTIA_NODE_RPC_PORT
        --daemon-dir /home/ubuntu/.elements
        --electrum-rpc-addr $APP_SEQUENTIA_ELECTRS_IP:$APP_SEQUENTIA_ELECTRS_RPC_PORT
        --http-addr $APP_SEQUENTIA_ELECTRS_IP:$APP_SEQUENTIA_ELECTRS_WEB_PORT
        --electrum-banner "Sequentia Testnet Electrum Server"
        --cors "*"
        --monitoring-addr $APP_SEQUENTIA_ELECTRS_IP:4225
      networks:
        default:
          ipv4_address: $APP_SEQUENTIA_ELECTRS_IP

  web:
    image: ghcr.io/sequentiaseq/sequentia-web:0.2@sha256:007fa1a89ee7cd387e694ea4c7b73a5c2036f0ca8c4f5b532fed91b8a2745b57
    user: "1000:1000"
    depends_on:
      - node
    restart: on-failure
    environment:
      RPC_USER: $APP_SEQUENTIA_RPC_USER
      RPC_PASS: $APP_SEQUENTIA_RPC_PASS
      RPC_HOST: $APP_SEQUENTIA_NODE_IP
      RPC_PORT: $APP_SEQUENTIA_NODE_RPC_PORT
      P2P_PORT: $APP_SEQUENTIA_NODE_P2P_PORT
      ELECTRUM_PORT: $APP_SEQUENTIA_ELECTRS_RPC_PORT
      # Remote
      REMOTE_RPC_HOST: $APP_SEQUENTIA_RPC_HIDDEN_SERVICE
      REMOTE_P2P_HOST: $APP_SEQUENTIA_P2P_HIDDEN_SERVICE
      REMOTE_ELECTRUM_HOST: $APP_SEQUENTIA_ELECTRS_HIDDEN_SERVICE
    networks:
      default:
        ipv4_address: $APP_SEQUENTIA_IP

  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - $APP_DATA_DIR/torrc:/etc/tor/torrc:ro
      - $TOR_DATA_DIR:/data
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: $APP_SEQUENTIA_TOR_PROXY_IP
